version: "3.9"
services:
  cert-bootstrap:
    image: "docker.sunet.se/knubbis/knubbis-cfssl-helper:2c862a34f0017e4e5c7b87847e666260ffd9383c"
    user: 1000000000:1000000000
    volumes:
      - /opt/knubbis-fleetlock/cert-bootstrap:/cert-bootstrap
      - /opt/knubbis-fleetlock/cert-bootstrap-ca:/cert-bootstrap-ca
      - /opt/knubbis-fleetlock/cert-bootstrap-etcd:/cert-bootstrap-etcd
    tmpfs:
      - /work:uid=1000000000
    command:
      - "/cert-bootstrap/bootstrap.sh"

  etcd:
    image: "gcr.io/etcd-development/etcd:v3.5.7"
    user: 1000000000:1000000000
    volumes:
      - /opt/knubbis-fleetlock/etcd-data:/etcd-data
      - /opt/knubbis-fleetlock/cert-bootstrap-etcd:/cert-bootstrap-etcd
    entrypoint: /usr/local/bin/etcd
    command:
      - "--data-dir=/etcd-data"
      - "--cert-file=/cert-bootstrap-etcd/etcd.pem"
      - "--key-file=/cert-bootstrap-etcd/etcd-key.pem"
      - "--self-signed-cert-validity=10"
      - "--listen-client-urls=https://0.0.0.0:2379"
      - "--advertise-client-urls=https://0.0.0.0:2379"
      - "--log-outputs=stderr"
      - "--auto-compaction-retention=1"
      - "--log-level=info"
    depends_on:
      cert-bootstrap:
        condition: service_completed_successfully

  etcd-bootstrap:
    image: "docker.sunet.se/knubbis/knubbis-etcdctl-helper:ac104668b10034e9ec47680633e565c264628e8b"
    user: 1000000000:1000000000
    volumes:
      - /opt/knubbis-fleetlock/etcd-bootstrap:/etcd-bootstrap
    command:
      - "/etcd-bootstrap/bootstrap.sh"
    depends_on:
      - etcd

  knubbis-fleetlock:
    image: "docker.sunet.se/knubbis/knubbis-fleetlock:f865257d08de94e00009908ce56a5e26cb96789b"
    user: 1000000001:1000000001
    ports:
      - "443:8443"
    volumes:
      - /opt/knubbis-fleetlock/conf:/conf
      - /opt/knubbis-fleetlock/cert-bootstrap-ca:/cert-bootstrap-ca
    depends_on:
      etcd-bootstrap:
        condition: service_completed_successfully
